apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: lab8
type: Opaque
data:
  DB_NAME: bXlkYg==        # mydb en base64
  DB_USER: bXl1c2Vy      # myuser en base64
  DB_PASSWORD: cGFzczEyMzQ=  # pass1234 en base64
